import { NextResponse } from 'next/server';import { z } from 'zod';import { createAIProvider } from '../../../../lib/ai/providers/provider';import { createMockProvider } from '../../../../lib/ai/providers/mock';import { AIError } from '../../../../lib/ai/errors';import { getPublicEnv } from '../../../../lib/config/env';import { createUserSupabaseClient, type UserDbClient } from '../../../../lib/supabase/server';
const schema=z.object({message:z.string().trim().min(1).max(2000),context:z.object({workouts:z.boolean().optional(),nutrition:z.boolean().optional(),recovery:z.boolean().optional(),body:z.boolean().optional()}).optional(),history:z.array(z.object({role:z.enum(['user','assistant']),text:z.string().max(4000)})).max(20).optional()});
const system='You are a practical fitness and nutrition coach. You are not a doctor, must not diagnose, must not provide emergency treatment, and should recommend professional help for concerning symptoms. Use the provided user data summary when answering. If the summary contains no data, say that clearly. Be specific: mention actual logged foods, workouts, recovery values, and body measurements when present. Include a short Data considered section.';
function compact(value:unknown){return JSON.stringify(value,(_,v)=>v===null||v===''||typeof v==='undefined'?undefined:v).slice(0,12000)}
async function getCoachData(db:UserDbClient,userId:string,ctx:Record<string,boolean|undefined>={}){const [workouts,nutrition,recovery,body]=await Promise.all([
 ctx.workouts?db.request<any[]>(`workout_sessions?user_id=eq.${userId}&select=id,started_at,finished_at,notes,workout_session_exercises(id,name,position,workout_sets(id,weight,reps,rpe,set_type))&order=started_at.desc&limit=10`).catch(e=>({error:e instanceof Error?e.message:'Failed to load workouts'})):Promise.resolve([]),
 ctx.nutrition?db.request<any[]>(`food_logs?user_id=eq.${userId}&select=id,logged_at,meal,name,calories,protein,carbohydrates,fat,fiber&order=logged_at.desc&limit=25`).catch(e=>({error:e instanceof Error?e.message:'Failed to load nutrition'})):Promise.resolve([]),
 ctx.recovery?db.request<any[]>(`recovery_checkins?user_id=eq.${userId}&select=id,checked_at,sleep_hours,sleep_quality,energy,stress,motivation,soreness,pain,pain_area,notes&order=checked_at.desc&limit=14`).catch(e=>({error:e instanceof Error?e.message:'Failed to load recovery'})):Promise.resolve([]),
 ctx.body?db.request<any[]>(`body_measurements?user_id=eq.${userId}&select=id,measured_at,weight_kg,body_fat_percent,waist_cm,chest_cm,shoulders_cm,neck_cm,left_arm_cm,right_arm_cm,hips_cm,left_thigh_cm,right_thigh_cm,notes&order=measured_at.desc&limit=20`).catch(e=>({error:e instanceof Error?e.message:'Failed to load body'})):Promise.resolve([]),
]);return{workouts,nutrition,recovery,body};}
export async function POST(req:Request){const parsed=schema.safeParse(await req.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({error:'Invalid AI chat request'},{status:400});const env=getPublicEnv();const data=parsed.data;const context=data.context??{workouts:true,nutrition:true,recovery:true,body:true};const dataConsidered=Object.entries(context).filter(([,v])=>v).map(([k])=>k);const provider=(env.aiProvider==='mock'||!env.openRouterConfigured)?createMockProvider({...process.env,AI_PROVIDER:'mock'}):createAIProvider(process.env);try{let userData:any={};try{const db=await createUserSupabaseClient();userData=await getCoachData(db,db.user.id,context);}catch(e){userData={error:e instanceof Error?e.message:'Could not load user data'};}const response=await provider.generateText({modelRole:'reasoning',temperature:.3,maxOutputTokens:900,messages:[{role:'system',content:system},{role:'user',content:`User question: ${data.message}\n\nAllowed data categories: ${dataConsidered.join(', ')||'none'}\n\nActual user data summary JSON:\n${compact(userData)}\n\nRecent chat history:\n${compact(data.history??[])}`}],metadata:{feature:'coach-chat',dataConsidered:dataConsidered.join(',')}});return NextResponse.json({provider:response.provider,model:response.model,content:response.content,dataConsidered,userData,usage:response.usage});}catch(e){const err=e instanceof AIError?e:new AIError('UNKNOWN','AI request failed');return NextResponse.json({error:err.message,code:err.code,suggestedFallback:'Switch AI_PROVIDER=mock or configure OpenRouter credentials.'},{status:err.code==='RATE_LIMITED'?429:502})}}
