'use client';
import { isSupabaseAvailable } from '../supabase/client';
import { demoBody, demoFoods, demoRecovery, demoWorkout, demoPlan, demoExercises } from './demo-data';
import { idbDelete, idbGet, idbGetAll, idbPut } from './browser-db';
import type { AppRepositories, ListRepository, SettingsRepository } from './types';

function apiRepo<T extends {id?: string}>(resource: string): ListRepository<T> { return { async list(){const r=await fetch(`/api/data/${resource}`); const j=await r.json(); if(!r.ok) throw new Error(j.error || 'Load failed'); return j.items ?? [];}, async save(item){const r=await fetch(`/api/data/${resource}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(item)}); const j=await r.json(); if(!r.ok) throw new Error(j.message || j.error || 'Save failed'); return j.item ?? item;}, async delete(id){const r=await fetch(`/api/data/${resource}?id=${encodeURIComponent(id)}`,{method:'DELETE'}); const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j.error || 'Delete failed');} }; }
function demoRepo<T extends {id?: string}>(store: string, seed: T[] = []): ListRepository<T> { return { async list(){const rows=await idbGetAll<T>(store); if(rows.length) return rows; for(const item of seed) await idbPut(store,{...item,syncState:'Saved locally' as const}); return idbGetAll<T>(store);}, async save(item){return idbPut(store,{...item,syncState:'Saved locally' as const});}, async delete(id){await idbDelete(store,id);} }; }
function apiSettings(): SettingsRepository { return { async get(){const r=await fetch('/api/data/settings'); const j=await r.json(); if(!r.ok) throw new Error(j.error || 'Load failed'); return j.item ?? {};}, async save(item){const r=await fetch('/api/data/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(item)}); const j=await r.json(); if(!r.ok) throw new Error(j.error || 'Save failed'); return item;} }; }
function demoSettings(store: string): SettingsRepository { return { async get(){return (await idbGet(store,'singleton')) ?? {id:'singleton',displayName:'Demo athlete',syncState:'Saved locally' as const};}, async save(item){return idbPut(store,{...item,id:'singleton',syncState:'Saved locally' as const});} }; }
export function createRepositories(): AppRepositories { const prod=isSupabaseAvailable(); return { foods: prod ? apiRepo('foods') : demoRepo('foods', demoFoods as any), body: prod ? apiRepo('body') : demoRepo('body', demoBody as any), recovery: prod ? apiRepo('recovery') : demoRepo('recovery', [demoRecovery as any]), workouts: prod ? apiRepo('workouts') : demoRepo('workouts', [demoWorkout as any]), exercises: prod ? apiRepo('exercises') : demoRepo('exercises', demoExercises as any), settings: prod ? apiSettings() : demoSettings('settings'), workoutPlans: prod ? apiRepo('workout-plans') : demoRepo('workout-plans', [demoPlan as any]), nutritionTargets: prod ? apiSettings() : demoSettings('nutrition-targets') }; }
export const repositories = createRepositories();
