export type Meal = 'breakfast'|'lunch'|'dinner'|'snacks'|'other';
export type SyncState = 'Saved locally'|'Syncing'|'Synced'|'Sync failed';
export type Food = {id?:string; loggedAt?:string; meal:Meal; name:string; calories?:number|null; protein?:number|null; carbohydrates?:number|null; carbs?:number|null; fat?:number|null; fiber?:number|null; notes?:string; photoPath?:string; syncState?:SyncState};
export type Body = {id?:string; measuredAt?:string; date?:string; weightKg?:number|null; bodyFatPercent?:number|null; waistCm?:number|null; chestCm?:number|null; leftArmCm?:number|null; rightArmCm?:number|null; leftThighCm?:number|null; rightThighCm?:number|null; hipsCm?:number|null; shouldersCm?:number|null; neckCm?:number|null; notes?:string; syncState?:SyncState};
export type Recovery = {id?:string; checkedAt?:string; sleepHours?:number|null; sleepQuality?:number|null; energy?:number|null; stress?:number|null; motivation?:number|null; soreness?:number|null; pain?:boolean; painArea?:string; notes?:string; syncState?:SyncState};
export type WorkoutSet = {id?:string; weight?:number|string|null; reps?:number|string|null; rpe?:number|string|null; setType?:'warm-up'|'working'|'drop'|'failure'|'custom'; type?:string; completed?:boolean; durationSeconds?:number|string|null; distanceMeters?:number|string|null; notes?:string};
export type WorkoutExercise = {id?:string; exerciseId?:string; name:string; position?:number; notes?:string; plannedSets?:number|null; plannedMinReps?:number|null; plannedMaxReps?:number|null; plannedRpe?:number|null; plannedRestSeconds?:number|null; sets:WorkoutSet[]};
export type Workout = {id?:string; planId?:string; planDayId?:string; startedAt?:string; date?:string; finishedAt?:string|null; notes?:string; exercises:WorkoutExercise[]; syncState?:SyncState};
export type MeasurementType = 'weight and reps'|'bodyweight and reps'|'duration'|'distance';
export type Exercise = {id?:string; name:string; muscleGroup?:string; primaryMuscleGroup?:string; secondaryMuscleGroups?:string[]; equipment?:string; category?:string; instructions?:string; notes?:string; defaultRestSeconds?:number|null; unilateral?:boolean; measurementType?:MeasurementType; archived?:boolean; syncState?:SyncState};
export type WorkoutPlanExercise = {id?:string; exerciseId?:string; exerciseName:string; position:number; targetSets?:number|null; minReps?:number|null; maxReps?:number|null; targetRpe?:number|null; restSeconds?:number|null; progressionType?:string; notes?:string; alternatives?:string[]};
export type WorkoutPlanDay = {id?:string; name:string; position:number; exercises:WorkoutPlanExercise[]};
export type WorkoutPlan = {id?:string; name:string; goal?:string; active?:boolean; archived?:boolean; days:WorkoutPlanDay[]; syncState?:SyncState};
export type Settings = {displayName?:string; goalType?:string; goalWeightKg?:number|null; timezone?:string; weekStartDay?:string; calorieTarget?:number|null; proteinTarget?:number|null; carbohydrateTarget?:number|null; fatTarget?:number|null; fiberTarget?:number|null; waterTargetMl?:number|null; syncState?:SyncState};
export type ResourceMap = {foods:Food; body:Body; recovery:Recovery; workouts:Workout; exercises:Exercise};
export interface ListRepository<T>{list():Promise<T[]>; save(item:T):Promise<T>; delete(id:string):Promise<void>}
export interface SettingsRepository{get():Promise<Settings>; save(item:Settings):Promise<Settings>}
export interface AppRepositories{foods:ListRepository<Food>; body:ListRepository<Body>; recovery:ListRepository<Recovery>; workouts:ListRepository<Workout>; exercises:ListRepository<Exercise>; settings:SettingsRepository; workoutPlans:ListRepository<WorkoutPlan>; nutritionTargets:SettingsRepository}
