import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { z } from "zod";
import { createMockProvider } from "../lib/ai/providers/mock";
import { buildOpenRouterRequest, normalizeOpenRouterMessageContent, normalizeOpenRouterResponse, createOpenRouterProvider } from "../lib/ai/providers/openrouter";
import { selectModel } from "../lib/ai/models";
import { enforceBudget } from "../lib/ai/usage";
import { buildPrivacyFilteredContext } from "../lib/ai/services/privacy-context";
import { AIError } from "../lib/ai/errors";

const messages = [{ role: "user" as const, content: "hi" }];
const env = { AI_PROVIDER: "openrouter", OPENROUTER_API_KEY: "key", AI_FAST_MODEL: "fast", AI_REASONING_MODEL: "reason", AI_VISION_MODEL: "vision", AI_FALLBACK_MODEL: "fallback" };

describe("provider contract", () => { it("mock generates text, structured data, and normalized stream", async () => { const provider = createMockProvider({ AI_PROVIDER: "mock" }); await expect(provider.generateText({ modelRole: "fast", messages })).resolves.toMatchObject({ provider: "mock" }); const schema = z.object({ result: z.string() }); await expect(provider.generateStructured({ modelRole: "fast", messages }, schema)).resolves.toMatchObject({ content: { result: "mock" } }); const reader = (await provider.streamText({ modelRole: "fast", messages })).getReader(); await expect(reader.read()).resolves.toMatchObject({ value: { type: "text-delta" } }); }); });

describe("OpenRouter normalization", () => { it("normalizes image parts", () => { expect(normalizeOpenRouterMessageContent([{ type: "image", url: "https://x/y.jpg", mimeType: "image/jpeg" }])).toEqual([{ type: "image_url", image_url: { url: "https://x/y.jpg" }, mime_type: "image/jpeg" }]); }); it("builds request with routing privacy controls and schema", () => { const req = buildOpenRouterRequest({ modelRole: "fast", messages, responseSchema: { type: "object" }, tools: [{ name: "get_recent_workouts", description: "Recent workouts", parameters: { type: "object" } }] }, { ...env, OPENROUTER_PROVIDER_ORDER: "a,b", OPENROUTER_ZDR_ONLY: "true" }); expect(req.body.provider).toMatchObject({ require_parameters: true, data_collection: "deny", zdr: true, order: ["a", "b"] }); expect(req.body.model).toBe("fast"); expect(req.body.response_format).toBeTruthy(); }); it("normalizes response usage", () => { expect(normalizeOpenRouterResponse({ id: "1", model: "m", choices: [{ message: { content: "ok" }, finish_reason: "stop" }], usage: { prompt_tokens: 1, completion_tokens: 2, total_tokens: 3, cost: 0.01 } }, "m")).toMatchObject({ content: "ok", usage: { totalTokens: 3, providerReportedCostUsd: 0.01 } }); }); });

describe("capabilities and fallback", () => { it("rejects unsupported capabilities", () => { expect(() => selectModel("fallback", ["vision"], { fallback: { id: "f", provider: "p", supportsVision: false, supportsTools: false, supportsStructuredOutput: true, supportsStreaming: false }, fast: { id: "a", provider: "p", supportsVision: false, supportsTools: false, supportsStructuredOutput: true, supportsStreaming: false }, reasoning: { id: "r", provider: "p", supportsVision: false, supportsTools: false, supportsStructuredOutput: true, supportsStreaming: false }, vision: { id: "v", provider: "p", supportsVision: false, supportsTools: false, supportsStructuredOutput: true, supportsStreaming: false } })).toThrow(AIError); }); });

describe("budget and privacy", () => { it("enforces daily cost budget", () => { expect(() => enforceBudget({ dailyUsd: 10, monthlyUsd: 10 }, { dailyBudgetUsd: 5 })).toThrow(/Daily/); }); it("filters disabled health context", () => { expect(buildPrivacyFilteredContext({ allowWorkoutData: true, allowNutritionData: false, allowBodyMeasurements: false, allowAppleHealthSummaries: false, allowMealPhotoAnalysis: false, allowProactiveMorningAnalysis: false, allowChatHistoryStorage: false }, { workouts: [1], nutrition: [2] })).toEqual({ workouts: [1] }); }); });

describe("timeout and retry", () => { beforeEach(() => vi.useFakeTimers()); afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks(); }); it("maps 429 to rate limit", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: false, status: 429 })); const provider = createOpenRouterProvider(env); await expect(provider.generateText({ modelRole: "fast", messages, timeoutMs: 1000 })).rejects.toMatchObject({ code: "RATE_LIMITED" }); }); });
