import { z, type ZodSchema } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { getAIConfig } from "../config";
import { AIError, toAIError } from "../errors";
import { createModelRegistry, selectModel } from "../models";
import type { AICapability, AIContentPart, AIProvider, AIRequestOptions, AIResponse, AIStreamEvent } from "../types";

export type OpenRouterOptions = { providerOrder?: string[]; allowFallbacks?: boolean; requireParameters?: boolean; dataCollection?: "allow" | "deny"; zeroDataRetentionOnly?: boolean; maxPrice?: { prompt?: number; completion?: number } };
const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));
export function normalizeOpenRouterMessageContent(content: string | AIContentPart[]) { return typeof content === "string" ? content : content.map(p => p.type === "text" ? { type: "text", text: p.text } : { type: "image_url", image_url: { url: p.url }, ...(p.mimeType ? { mime_type: p.mimeType } : {}) }); }
export function buildOpenRouterRequest(options: AIRequestOptions, env: Record<string, string | undefined> = process.env) { const cfg = getAIConfig(env); const required: AICapability[] = [...(options.requiredCapabilities || []), ...(options.responseSchema ? ["structuredOutput" as const] : []), ...(options.tools?.length ? ["tools" as const] : []), ...(options.stream ? ["streaming" as const] : [])]; const model = selectModel(options.modelRole, required, createModelRegistry(env)); const provider: Record<string, unknown> = { allow_fallbacks: cfg.openrouter.allowFallbacks, require_parameters: cfg.openrouter.requireParameters || required.length > 0, data_collection: cfg.openrouter.dataCollection, zdr: cfg.openrouter.zeroDataRetentionOnly }; if (cfg.openrouter.providerOrder?.length) provider.order = cfg.openrouter.providerOrder; if (cfg.openrouter.maxPromptPrice || cfg.openrouter.maxCompletionPrice) provider.max_price = { prompt: cfg.openrouter.maxPromptPrice, completion: cfg.openrouter.maxCompletionPrice };
 return { url: `${cfg.openrouter.baseUrl.replace(/\/$/, "")}/chat/completions`, model, body: { model: model.id, messages: options.messages.map(m => ({ ...m, content: normalizeOpenRouterMessageContent(m.content) })), temperature: options.temperature, max_tokens: options.maxOutputTokens, stream: options.stream || false, tools: options.tools?.map(t => ({ type: "function", function: { name: t.name, description: t.description, parameters: t.parameters } })), response_format: options.responseSchema ? { type: "json_schema", json_schema: { name: "response", strict: true, schema: options.responseSchema } } : undefined, provider, metadata: options.metadata } };
}
export function normalizeOpenRouterResponse(json: any, model: string): AIResponse<string> { const usage = json.usage ? { inputTokens: json.usage.prompt_tokens, outputTokens: json.usage.completion_tokens, totalTokens: json.usage.total_tokens, providerReportedCostUsd: json.usage.cost } : undefined; return { id: json.id, provider: "openrouter", model: json.model || model, content: json.choices?.[0]?.message?.content ?? "", finishReason: json.choices?.[0]?.finish_reason, usage, rawProviderMetadata: { created: json.created } }; }
async function fetchWithRetry(url: string, init: RequestInit, retries: number, timeoutMs: number) { for (let i=0;i<=retries;i++) { const ctrl = new AbortController(); const timeout = setTimeout(() => ctrl.abort(), timeoutMs); try { const res = await fetch(url, { ...init, signal: ctrl.signal }); clearTimeout(timeout); if ([401,403].includes(res.status)) throw new AIError("AUTHENTICATION_FAILED", "AI provider authentication failed"); if (res.status === 429) throw new AIError("RATE_LIMITED", "AI provider rate limited the request"); if (res.status >= 500 && i < retries) { await sleep(50 * 2 ** i); continue; } if (!res.ok) throw new AIError("PROVIDER_UNAVAILABLE", `AI provider returned ${res.status}`); return res; } catch (e) { clearTimeout(timeout); const err = e instanceof Error && e.name === "AbortError" ? new AIError("TIMEOUT", "AI request timed out", e) : toAIError(e); if (["AUTHENTICATION_FAILED","RATE_LIMITED"].includes(err.code) || i === retries) throw err; await sleep(50 * 2 ** i); } } throw new AIError("UNKNOWN", "Retry loop exited unexpectedly"); }
export function createOpenRouterProvider(env: Record<string, string | undefined> = process.env): AIProvider { const cfg = getAIConfig(env); const headers: Record<string,string> = { Authorization: `Bearer ${cfg.openrouter.apiKey}`, "Content-Type": "application/json" }; if (cfg.openrouter.siteUrl) headers["HTTP-Referer"] = cfg.openrouter.siteUrl; if (cfg.openrouter.appName) headers["X-Title"] = cfg.openrouter.appName; return { supports: () => true, async generateText(options) { const req = buildOpenRouterRequest(options, env); const res = await fetchWithRetry(req.url, { method: "POST", headers, body: JSON.stringify(req.body) }, cfg.maxRetries, options.timeoutMs || cfg.requestTimeoutMs); return normalizeOpenRouterResponse(await res.json(), req.model.id); }, async generateStructured<T>(options: AIRequestOptions, schema: ZodSchema<T>) { const responseSchema = options.responseSchema || zodToJsonSchema(schema, "response") as Record<string, unknown>; const text = await this.generateText({ ...options, responseSchema, requiredCapabilities: [...(options.requiredCapabilities || []), "structuredOutput"] }); try { return { ...text, content: schema.parse(JSON.parse(text.content)) }; } catch (e) { throw new AIError("INVALID_STRUCTURED_OUTPUT", "Provider returned invalid structured output", e); } }, async streamText(options) { const text = await this.generateText({ ...options, stream: false }); return new ReadableStream<AIStreamEvent>({ start(c) { c.enqueue({ type: "text-delta", text: text.content }); if (text.usage) c.enqueue({ type: "usage", usage: text.usage }); c.enqueue({ type: "complete" }); c.close(); } }); } }; }
export const HealthCheckSchema = z.object({ ok: z.boolean() });
