'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { QueryKey } from '@tanstack/react-query';
import { Card } from '../components/ui/Card';
import { SyncState } from '../lib/repositories/types';
import type { ListRepository } from '../lib/repositories/types';
export { Card };
export function n(v: unknown){if(v===''||v==null)return undefined;const x=Number(String(v).replace(',','.'));return Number.isNaN(x)?v:x}
export function dtLocal(d=new Date()){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
export function Field({label,value,onChange,type='text',error}:{label:string;value:unknown;onChange:(v:string)=>void;type?:string;error?:string}){return <label><span>{label}</span><input className="input" type={type} inputMode={type==='number'?'decimal':undefined} step={type==='number'?'any':undefined} value={value == null ? '' : String(value)} onChange={e=>onChange(e.currentTarget.value)}/>{error&&<small className="error">{error}</small>}</label>}
export function MiniChart({values}:{values:number[]}){const max=Math.max(1,...values);return <div className="chart">{values.map((v,i)=><span key={i} style={{height:`${Math.max(8,v/max*80)}px`}} title={`${v}`}/>)}</div>}
export function SyncBadge({state,isFetching,error}:{state?:SyncState;isFetching?:boolean;error?:unknown}){const text=error?'Sync failed':isFetching?'Syncing':state ?? 'Synced';return <p className={error?'error':'muted'}>{text}</p>}
export function useListResource<T extends {id?: string; syncState?: SyncState}>(key: QueryKey, repo: ListRepository<T>){ const qc=useQueryClient(); const query=useQuery({queryKey:key, queryFn:()=>repo.list()}); const save=useMutation({ mutationFn:(item:T)=>repo.save(item), onMutate:async(item)=>{await qc.cancelQueries({queryKey:key}); const prev=qc.getQueryData<T[]>(key)??[]; const optimistic={...item,id:item.id??`local-${crypto.randomUUID()}`,syncState:'Syncing' as SyncState}; qc.setQueryData<T[]>(key, item.id ? prev.map(x=>x.id===item.id?optimistic:x) : [optimistic,...prev]); return {prev};}, onError:(_e,_v,ctx)=>{if(ctx?.prev) qc.setQueryData(key,ctx.prev);}, onSuccess:(saved)=>{qc.setQueryData<T[]>(key,(old=[])=>old.map(x=>x.id===saved.id||x.id?.startsWith('local-')?{...saved,syncState:saved.syncState??'Synced'}:x));}, onSettled:()=>qc.invalidateQueries({queryKey:key}) }); const del=useMutation({ mutationFn:(id:string)=>repo.delete(id), onMutate:async(id)=>{await qc.cancelQueries({queryKey:key}); const prev=qc.getQueryData<T[]>(key)??[]; qc.setQueryData<T[]>(key, prev.filter(x=>x.id!==id)); return {prev};}, onError:(_e,_v,ctx)=>{if(ctx?.prev) qc.setQueryData(key,ctx.prev);}, onSettled:()=>qc.invalidateQueries({queryKey:key}) }); return {items:query.data??[], loading:query.isLoading, isFetching:query.isFetching || save.isPending || del.isPending, error:query.error || save.error || del.error, save:(item:T)=>save.mutateAsync(item), del:(id?:string)=>id?del.mutateAsync(id):Promise.resolve()}; }
