'use client';
import { useEffect, useState } from 'react';
import { calculateWorkoutVolume, estimateOneRepMax } from '../../../lib/calculations/health';
import { idbGet, idbPut } from '../../../lib/repositories/browser-db';
import { repositories } from '../../../lib/repositories/factory';
import type { Workout } from '../../../lib/repositories/types';
import { queryKeys } from '../../../lib/query/keys';
import { Card, Field, SyncBadge, n, useListResource } from '../../shared';
export function GymPage(){const api=useListResource<Workout>(queryKeys.workouts,repositories.workouts);const[active,setActiveState]=useState<Workout|null>(null);function setActive(w:Workout|null){setActiveState(w); void idbPut('active-workout',{id:'active',workout:w});}useEffect(()=>{idbGet<{workout:Workout|null}>('active-workout','active').then(saved=>setActiveState(saved?.workout ?? api.items.find(w=>!w.finishedAt) ?? null));},[api.items]);function start(){setActive({startedAt:new Date().toISOString(),notes:'',exercises:[{name:'Bench press',sets:[]}]})}function addSet(i:number){if(!active)return;setActive({...active,exercises:active.exercises.map((e,idx)=>idx===i?{...e,sets:[...e.sets,{weight:'',reps:'',rpe:'',setType:'working',completed:false}]}:e)})}async function save(finish=false){if(!active)return;await api.save({...active,finishedAt:finish?new Date().toISOString():active.finishedAt});if(finish)setActive(null)}const history=api.items.filter(w=>w.finishedAt);return <div className="grid"><Card><p className="eyebrow">Gym</p><button className="btn" onClick={start}>Start empty workout</button><SyncBadge isFetching={api.isFetching} error={api.error}/>{api.error&&<p className="error">{api.error.message}</p>}</Card>{active&&<Card><h3>Active workout</h3><p className="muted">Saved locally</p><button className="btn secondary" onClick={()=>setActive({...active,exercises:[...active.exercises,{name:'New exercise',sets:[]}]})}>Add exercise</button>{active.exercises.map((e,i)=><div className="card" key={i}><Field label="Exercise" value={e.name} onChange={v=>setActive({...active,exercises:active.exercises.map((x,j)=>j===i?{...x,name:v}:x)})}/><button className="btn secondary" onClick={()=>addSet(i)}>Add set</button>{e.sets.map((s,j)=><div className="grid two" key={j}>{['weight','reps','rpe'].map(k=><Field key={k} label={k} type="number" value={(s as any)[k]} onChange={v=>setActive({...active,exercises:active.exercises.map((x,xi)=>xi===i?{...x,sets:x.sets.map((y,yi)=>yi===j?{...y,[k]:n(v)}:y)}:x)})}/>)}</div>)}</div>)}<button className="btn" onClick={()=>save(false)}>Save active workout</button><button className="btn" onClick={()=>save(true)}>Finish workout</button></Card>}<Card><p className="eyebrow">History</p>{history.map(w=><p key={w.id}>{new Date(w.startedAt??w.date??'').toLocaleDateString()} · {calculateWorkoutVolume(w as any)} kg volume <button onClick={()=>setActive(w)}>Edit</button> <button onClick={()=>api.del(w.id)}>Delete</button></p>)}<p>e1RM example from latest set: {estimateOneRepMax(80,6)}kg</p></Card></div>}
